dataloader_cfg:
  loadertype: !!python/name:dataloaders.neko_joint_loader.NekoJointLoader ''
  subsets:
    dan_mth1200:
      dl_args:
        batch_size: 32
        num_workers: 8
        shuffle: false
      ds_args:
        global_state: Train
        img_height: 320
        img_width: 32
        maxT: 40
        qhb_aug: false
        roots:
        - /home/izhangxm/mnt/hotssd/recdatassd/MTH1200
        transform: !!python/object:torchvision.transforms.transforms.Compose
          transforms:
          - !!python/object:torchvision.transforms.transforms.ToTensor {}
      type: !!python/name:neko_2020nocr.dan.dataloaders.dataset_scene.ColoredLmdbDatasetV ''
iterkey: Top Nep
modules:
  DTD:
    args:
      with_optim: false
    modular: !!python/name:neko_2021_mjt.configs.modules.config_dtd_xos_mk5.get_dtdmk5_xos ''
    save_each: 20000
  GA:
    args:
      num_channels: 32
      with_optim: true
    modular: !!python/name:neko_2021_mjt.configs.modules.config_sa.get_sa_mk3 ''
    save_each: 20000
  Latin_62_sampler:
    args:
      meta_args:
        case_sensitive: false
        meta_path: /home/izhangxm/mnt/hotssd/recdatassd/dicts/mth1200_train.pt
      sampler_args:
        max_batch_size: 256
        neg_servant: true
        val_frac: 0.8
      with_optim: false
    modular: !!python/name:neko_2021_mjt.configs.modules.config_ocr_sampler.get_meta_holder ''
    save_each: 0
  TA:
    args:
      cam_ch: 64
      maxT: 40
      num_channels: 512
      scales:
      - - 32
        - 16
        - 64
      - - 128
        - 8
        - 32
      - - 512
        - 8
        - 32
      with_optim: true
    modular: !!python/name:neko_2021_mjt.configs.modules.config_cam_stop.get_cam_stop ''
    save_each: 20000
  feature_extractor_cco:
    args:
      container: feature_extractor_container
      name: res1
    bogo_mod: &id002 !!python/name:neko_2021_mjt.bogo_modules.res45_binorm_bogomod.neko_res45_binorm_bogo ''
  feature_extractor_container:
    args:
      bn_names:
      - bn1
      - bn2
      - bn3
      bogo_names: &id001
      - res1
      - res2
      - res3
      expf: 1
      ich: 3
      input_shape: null
      ouch: 512
      strides: null
      with_optim: true
    modular: !!python/name:neko_2021_mjt.configs.modules.config_fe_db.get_dan_r45_binorm_orig ''
    provides_bogo_modules: *id001
    save_each: 20000
  feature_extractor_proto:
    args:
      container: feature_extractor_container
      name: res2
    bogo_mod: *id002
  loss_cls_emb:
    args:
      reduction: true
      wcls: 1
      wemb: 0
    modular: !!python/name:neko_2021_mjt.configs.modules.config_cls_emb_loss.get_loss_cls_emb2 ''
    save_each: 0
  pred:
    args:
      with_optim: true
    modular: !!python/name:neko_2021_mjt.configs.modules.config_ospred.get_link_xos ''
    save_each: 20000
  prototyper:
    args:
      backbone: feature_extractor_proto
      cam: GA
      capacity: 256
      drop: null
      force_proto_shape: null
      sp_proto: sp_proto
    bogo_mod: !!python/name:neko_2021_mjt.bogo_modules.prototype_gen3.PrototyperGen3 ''
root: runtime/OSTR_C2J_DTA_Only_MTH/mth_1200/jtrmodels
routine_cfgs:
  mjst:
    inp_cvt_dicts:
      image: dan_mth1200_image
      label: dan_mth1200_label
    log_each: 200
    log_path: runtime/OSTR_C2J_DTA_Only_MTH/mth_1200/logs/
    maxT: 40
    mod_cvt_dicts:
      CAM: TA
      feature_extractor: feature_extractor_cco
      losses:
      - loss_cls_emb
      preds:
      - pred
      prototyper: prototyper
      sampler: Latin_62_sampler
      seq: DTD
    name: mjst
    routine: !!python/name:neko_2021_mjt.routines.ocr_routines.mk7.osdan_routine_mk7.NekoHDOS2cRoutineCfmk7dtf ''
    stream: base_mth1200_
tasks:
  close_set_benchmarks:
    datasets:
      case_sensitive: false
      datasets:
        MTH1200:
          dl_args:
            batch_size: 128
            num_workers: 8
            shuffle: false
          ds_args:
            global_state: Test
            img_height: 320
            img_width: 32
            maxT: 40
            roots:
            - /home/izhangxm/mnt/hotssd/recdatassd/MTH1200
            transform: !!python/object:torchvision.transforms.transforms.Compose
              transforms:
              - !!python/object:torchvision.transforms.transforms.ToTensor {}
          type: !!python/name:neko_2020nocr.dan.dataloaders.dataset_scene.ColoredLmdbDatasetT ''
      dict_dir: null
      te_case_sensitive: false
    protoname: prototyper
    routine_cfgs:
      inp_cvt_dicts:
        image: image
        label: label
        plabel: plabel
        proto: proto
        tdict: tdict
      log_path: runtime/OSTR_C2J_DTA_Only_MTH/mth_1200/logs/
      maxT: 40
      measure_rej: false
      mod_cvt_dicts:
        CAM: TA
        feature_extractor: feature_extractor_cco
        losses:
        - loss_cls_emb
        preds:
        - pred
        prototyper: prototyper
        sampler: Latin_62_sampler
        seq: DTD
      name: close_set_benchmark
      routine: !!python/name:neko_2021_mjt.routines.ocr_routines.mk7.osdan_routine_mk7.NekoHDOS2cEvalRoutineCfmk7 ''
    temeta:
      case_sensitive: false
      meta_path: /home/izhangxm/mnt/hotssd/recdatassd/dicts/mth1200_train.pt
    type: !!python/name:neko_2021_mjt.eval_tasks.dan_eval_tasks.NekoOdanEvalTasks ''
val_each: 10000
vepoch: 2
vitr: 200000
